In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn  as sns

In [2]:
df = pd.read_csv("/Users/majid/Downloads/Datasets/iris.csv")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.size

750

In [5]:
df.shape

(150, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
df.isna()

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [10]:
df.notnull()

sepal_length  sepal_width  petal_length  petal_width  species
0            True         True          True         True     True
1            True         True          True         True     True
2            True         True          True         True     True
3            True         True          True         True     True
4            True         True          True         True     True
..            ...          ...           ...          ...      ...
145          True         True          True         True     True
146          True         True          True         True     True
147          True         True          True         True     True
148          True         True          True         True     True
149          True         True          True         True     True

[150 rows x 5 columns]

In [11]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [14]:
df['species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [15]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [16]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [17]:
x = df[["sepal_length" , "sepal_width" , "petal_length" , "petal_width"]]
y = df['species']

In [18]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [19]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,train_size = 0.8 , random_state = 42)

In [21]:
x_train

sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [22]:
x_test

sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4
31            5.4          3.4           1.5          0.4
64            5.6          2.9           3.6          1.3
141           6.9          3.1           5.1          2.3
68            6.2          2.2           4.5          1.5
82            5.8          2.7           3.9          1.2
110           6.5          3.2           5.1          2.0
12            4.8          3.0           1.4          0.1
36            5.5          3.5           1.3          0.2
9             4.9          3.1           1.5          0.1
19            5.1          3.8           1.5          0.3
56            6.3          3.3           4.7          1.6
104           6.5          3.0           5.8          2.2
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
132           6.4          2.8           5.6          2.2
29            4.7          3.2           1.6          0.2
127           6.1          3.0           4.9          1.8
26            5.0          3.4           1.6          0.4
128           6.4          2.8           5.6          2.1
131           7.9          3.8           6.4          2.0
145           6.7          3.0           5.2          2.3
108           6.7          2.5           5.8          1.8
143           6.8          3.2           5.9          2.3
45            4.8          3.0           1.4          0.3
30            4.8          3.1           1.6          0.2

In [23]:
y_train

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: species, Length: 120, dtype: int64

In [25]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: species, dtype: int64

##   GaussianNB

In [116]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [117]:
model

GaussianNB()

In [118]:
model.fit(x_train , y_train)

GaussianNB()

In [119]:
y_pred = model.predict(x_test)

In [120]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [121]:
model.score (x_test ,  y_pred)

1.0

In [144]:
from sklearn.metrics import mean_absolute_error ,mean_squared_error ,  accuracy_score , classification_report , recall_score , precision_score , f1_score , confusion_matrix 
mae = mean_absolute_error(y_test , y_pred)
mse = mean_squared_error(y_test , y_pred)
rmse = np.sqrt(mse)
acc = accuracy_score(y_test , y_pred)
cr = classification_report(y_test , y_pred)
cm = confusion_matrix(y_test , y_pred)
rs = recall_score(y_test , y_pred , average = 'macro')
ps = precision_score(y_test , y_pred , average = 'macro')
fs = f1_score(y_test , y_pred , average = 'macro')
error_rate = 1 - acc

In [145]:
print("Mean Absolute Error : " ,mae)

Mean Absolute Error :  0.1


In [146]:
print("Mean Sqaured error :" , mse)

Mean Sqaured error : 0.1


In [147]:
print("Root mean squared error :" ,rmse)

Root mean squared error : 0.31622776601683794


In [148]:
print("Accuracy : " , acc*100 )

Accuracy :  90.0


In [149]:
print("Classification_report : \n " , cr)

Classification_report : 
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [150]:
print("Confusion Matrix: \n " ,cm )

Confusion Matrix: 
  [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [151]:
print("recall score :" ,rs)

recall score : 0.9090909090909092


In [152]:
print ("Precision_score :",ps)

Precision_score : 0.9166666666666666


In [153]:
print("F1 score :",fs)

F1 score : 0.899749373433584


In [154]:
print("Error Rate : " ,error_rate)

Error Rate :  0.09999999999999998


## Multinomial NB

In [155]:
from sklearn.naive_bayes import MultinomialNB
model1 = MultinomialNB()

In [156]:
model1

MultinomialNB()

In [157]:
model1.fit(x_train , y_train)

MultinomialNB()

In [158]:
y_pred = model1.predict(x_test)

In [159]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 1, 2, 2, 2, 0, 0])

In [160]:
model1.score(x_test , y_pred)

1.0

In [161]:
from sklearn.metrics import mean_absolute_error ,mean_squared_error ,  accuracy_score , classification_report , recall_score , precision_score , f1_score , confusion_matrix 
mae = mean_absolute_error(y_test , y_pred)
mse = mean_squared_error(y_test , y_pred)
rmse = np.sqrt(mse)
acc = accuracy_score(y_test , y_pred)
cr = classification_report(y_test , y_pred)
cm = confusion_matrix(y_test , y_pred)
rs = recall_score(y_test , y_pred , average = 'macro')
ps = precision_score(y_test , y_pred , average = 'macro')
fs = f1_score(y_test , y_pred , average = 'macro')
error_rate = 1 - acc

In [165]:
mae

0.1

In [166]:
mse

0.1

In [167]:
rmse

np.float64(0.31622776601683794)

In [168]:
acc

0.9

In [170]:
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [171]:
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  3,  8]])

In [172]:
rs

0.9090909090909092

In [173]:
ps

0.9166666666666666

In [174]:
fs

0.899749373433584

In [175]:
error_rate

0.09999999999999998

## BernoulliNB

In [178]:
from sklearn.naive_bayes import BernoulliNB
model2 = BernoulliNB()

In [179]:
model2

BernoulliNB()

In [180]:
model2.fit(x_train , y_train)

BernoulliNB()

In [181]:
y_pred = model2.predict(x_test)

In [182]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [184]:
import warnings 
warnings.filterwarnings('ignore')

In [185]:
from sklearn.metrics import mean_absolute_error ,mean_squared_error ,  accuracy_score , classification_report , recall_score , precision_score , f1_score , confusion_matrix 
mae = mean_absolute_error(y_test , y_pred)
mse = mean_squared_error(y_test , y_pred)
rmse = np.sqrt(mse)
acc = accuracy_score(y_test , y_pred)
cr = classification_report(y_test , y_pred)
cm = confusion_matrix(y_test , y_pred)
rs = recall_score(y_test , y_pred , average = 'macro')
ps = precision_score(y_test , y_pred , average = 'macro')
fs = f1_score(y_test , y_pred , average = 'macro')
error_rate = 1 - acc

In [187]:
mae

0.7

In [188]:
mse

0.7

In [190]:
rmse

np.float64(0.8366600265340756)

In [191]:
acc

0.3

In [192]:
print(cr)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



In [193]:
cm

array([[ 0, 10,  0],
       [ 0,  9,  0],
       [ 0, 11,  0]])

In [194]:
rs

0.3333333333333333

In [195]:
ps

0.09999999999999999

In [196]:
fs

0.15384615384615385

In [197]:
error_rate

0.7